--- #YAML:1.0
name:                String-Rexx
version:             0.07
abstract:            Perl implementation of Rexx string functions
license:             perl
author:              
    - Ioannis Tambouras <ioannis@earthlink.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Params::Validate:              0
    Regexp::Common:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
