.PHONY: $(shell ls)
.SILENT: 

#all:  00_main.t      01_wordlength.t    02_words.t  
#all:  03_subword.t   04_strip.t         05_Substr.t
#all:  06_word.t      07_verify.t        08_space.t
#all:  09_reverse.t   10_right.t         11_Pos.t  
#all:  12_overlay.t   13_Length.t        14_left.t
#all:  15_lastpos.t   16_insert.t        17_delword.t
#all:  18_delstr.t    19_countstr.t      20_copies.t
#all:  21_compare.t   22_changestr.t     23_center.t
#all:  24_xrange.t                       26_translate.t

#all:  25_wordindex.t
#all:   01_wordlength.t
#all:   00_main.t
#all:   27_datatype.t
all:   28_wordpos.t

0*t 1*t 2*t:
	perl -w -Mstrict -Mblib $@  

